// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjEMvvAMaaamfrx6NvechfxYuK_oNXKnk',
    appId: '1:194920375058:web:1d96d7dbad1a80f48c09cb',
    messagingSenderId: '194920375058',
    projectId: 'positeams-programmierung2',
    authDomain: 'positeams-programmierung2.firebaseapp.com',
    storageBucket: 'positeams-programmierung2.appspot.com',
    measurementId: 'G-41V8E38997',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0aaLYalf1WlINzum7bA2MrJeX3Alanaw',
    appId: '1:194920375058:android:daddae12200efe518c09cb',
    messagingSenderId: '194920375058',
    projectId: 'positeams-programmierung2',
    storageBucket: 'positeams-programmierung2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDf4Yp6eM4Ajhhtq3Rl2TKfvYFtryyfWms',
    appId: '1:194920375058:ios:680c88280f7f01248c09cb',
    messagingSenderId: '194920375058',
    projectId: 'positeams-programmierung2',
    storageBucket: 'positeams-programmierung2.appspot.com',
    iosBundleId: 'com.example.positeamsProgrammierung2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDf4Yp6eM4Ajhhtq3Rl2TKfvYFtryyfWms',
    appId: '1:194920375058:ios:680c88280f7f01248c09cb',
    messagingSenderId: '194920375058',
    projectId: 'positeams-programmierung2',
    storageBucket: 'positeams-programmierung2.appspot.com',
    iosBundleId: 'com.example.positeamsProgrammierung2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjEMvvAMaaamfrx6NvechfxYuK_oNXKnk',
    appId: '1:194920375058:web:94ebd70e3664067c8c09cb',
    messagingSenderId: '194920375058',
    projectId: 'positeams-programmierung2',
    authDomain: 'positeams-programmierung2.firebaseapp.com',
    storageBucket: 'positeams-programmierung2.appspot.com',
    measurementId: 'G-J77TJEC0PT',
  );
}
